ULOGA_KORISNIK = "korisnik"
ULOGA_PRODAVAC = "prodavac"
ULOGA_ADMIN = "admin"

PUTANJA_KORSINICI = "./podaci/korisnici.csv"
PUTANJA_LETOVI = "./podaci/letovi.csv"
PUTANJA_KARTE = "./podaci/karte.csv"

PONEDELJAK = "ponedeljak"
UTORAK = "utorak"
SREDA = "sreda"
CETVRTAK = "cetvrtak"
PETAK = "petak"
SUBOTA = "subota"
NEDELJA = "nedelja"
